feat: vectis events
nymlab/vectis pull request #117
Opened 2022-12-08 08:58 UTC by j0nl1

DAO-TUNNEL

- instantiate -> vectis.dao_tunnel.v1.MsgInstantiate
  - contract_address
- add_approved_controller -> vectis.dao_tunnel.v1.MsgAddApprovedController
  - connection_id
  - port_id
- remove_approved_controller -> vectis.dao_tunnel.v1.MsgRemoveApprovedController
  - connection_id
  - port_id
- update_dao -> vectis.dao_tunnel.v1.MsgUpdateDaoAddr
  - address
- update_govec -> vectis.dao_tunnel.v1.MsgUpdateGovecAddr
  - address
- update_ibc_transfer_channel -> vectis.dao_tunnel.v1.MsgUpdateIbcTransferRecieverChannel
  - connection_id
  - channel_id
- dispatch_to_remote_tunnel -> vectis.dao_tunnel.v1.MsgDispatchActionOnRemoteTunnel
  - channel_id
  - job_id
- ibc_transfer -> vectis.dao_tunnel.v1.MsgIbcTransfer
  - to
  - channel_id
  - amount // should be casted to number //
  - denom

FACTORY/REMOTE_FACTORY

- instantiate -> vectis.factory.v1.MsgInstantiate
  - contract_address
- create_wallet -> vectis.factory.v1.MsgCreateWallet
  - wallet_id
- migrate_wallet -> vectis.factory.v1.MsgMigrateWallet
- update_code_id -> vectis.factory.v1.MsgUpdateCodeId"
  - type ?
  - code_id // should be casted to number //
- update_config_fee -> vectis.factory.v1.MsgUpdateConfigFee
  - type ?
  - amount // should be casted to number //
  - denom
- claim_govec -> vectis.factory.v1.MsgClaimGovec
  - proxy_address
- govec_minted -> vectis.factory.v1.MsgGovecMinted
  - proxy_address
  - minted -> success | failed

PROXY

- instantiate -> vectis.proxy.v1.MsgInstantiate
  - controller_address
  - multisig_code_id // should be casted to number //
  - code_id // should be casted to number //
  - label
  - relayers ?
  - guardians ?
- execute -> vectis.proxy.v1.MsgExecute
- relay -> vectis.proxy.v1.MsgRelay
- add_relayer -> vectis.proxy.v1.MsgAddRelayer
  - address
- remove_relaer -> vectis.proxy.v1.MsgRemoveRelayer
  - address
- freeze_status -> vectis.proxy.v1.MsgRevertFreezeStatus
  - status -> frozen | unfrozen
- rotate_controller_key -> vectis.proxy.v1.MsgRotateControlKey
  - old_address
  - new_address
- update_guardians -> vectis.proxy.v1.MsgUpdateGuardians
  - guaridans
  - multisg // should be casted to boolean //
  - multisig_code_id -> optional
- request_update_guardian -> vectis.proxy.v1.MsgRequestUpdateGuardians
  - create // should be casted to boolean //
  - guardians -> optional
- update label -> vectis.proxy.v1.MsgUpdateLabel
  - label
- reply -> MsgReplyMultisigInstantiate
  - contract_address
  - multisig_address
  - multisig_code_id // should be casted to number //

REMOTE TUNNEl

- dispatch -> vectis.remote-tunnel.v1.MsgDispatch
  - job_id
- ibc-transfer -> vectis.ibc-transfer.v1.MsgIbcTransfer
  - channel_id
  - to
  - amount
  - denom

2022-12-08 20:39 UTC, j0nl1 commented
https://github.com/nymlab/vectis-subquery/commit/fa83b3d6a1fc7a47faa97e62d4cbf8c119d4be4f

2022-12-12 05:08 UTC, whalelephant requested changes

2022-12-12 05:08 UTC, whalelephant commented on contracts/proxy/src/contract.rs
> +                .add_attribute("contract_address", env.contract.address)
why do we have this contract address in these events in the proxy particularly? Can parse in event metadata, not attributes?

2022-12-12 05:08 UTC, whalelephant commented on packages/vectis/src/func/factory.rs
> +        .add_attribute("contract_address", env.contract.address);
Again, why do we have to emit deliberate contract_address?

2022-12-16 10:02 UTC, whalelephant approved these changes

2022-12-16 10:19 UTC, merged